import Head from "next/head";
import Image from "next/image";
import { FaTrash } from "react-icons/fa";

import styles from "../styles/Cart.module.css";

import { useCart } from "../hooks/useCart";

import products from "../products.json";

const Cart = () => {
  const { cartItems, subtotal, checkout } = useCart();

  return (
    <div className={styles.container}>
      <Head>
        <title>Space Jelly Shop - Cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Cart</h1>

        <p className={styles.description}>
          Review your products before checkout.
        </p>

        <table className={styles.table}>
          <thead>
            <tr>
              <th>Product</th>
              <th>Amount</th>
              <th>Subtotal</th>
            </tr>
          </thead>
          <tbody>
            {cartItems.map((cartItem) => {
              const product = products.find(({ id }) => id === cartItem.id);

              if (!product) return;

              return (
                <tr key={product.id}>
                  <td className={styles.productInfo}>
                    <img src={product.image} alt={product.title} />
                    <div>
                      <strong>{product.title}</strong>
                      <span>R${product.price}</span>
                    </div>
                  </td>
                  <td>{cartItem.quantity}</td>
                  <td>
                    <strong>
                      R${cartItem.pricePerItem * cartItem.quantity}
                    </strong>
                  </td>
                  <td>
                    <FaTrash />
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>

        <div className={styles.checkout}>
          <span>
            <b>TOTAL:</b> R${subtotal}
          </span>
          <button className={styles.button} onClick={checkout}>
            Checkout
          </button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Cart;
