import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { initiateCheckout } from "../lib/payments";

import products from "../products.json";

interface IProduct {
  id: string;
  quantity: number;
}

interface ICart {
  products: IProduct[];
}

const defaultCart = {
  products: [],
};

export default function Home() {
  const [cart, setCart] = useState<ICart>(defaultCart);

  const cartItems = cart.products.map((cartProduct) => {
    const product = products.find(({ id }) => id === cartProduct.id);

    return {
      ...cartProduct,
      pricePerItem: product?.price,
    };
  });

  const subtotal = cartItems.reduce(
    (accumulator, { pricePerItem = 0, quantity }) => {
      return accumulator + pricePerItem * quantity;
    },
    0
  );

  const totalItems = cartItems.reduce((accumulator, { quantity }) => {
    return accumulator + quantity;
  }, 0);

  function addToCart({ id }: { id: string }): void {
    setCart((previous) => {
      let cartState = { ...previous };

      const productIndex = cartState.products.findIndex(
        (product) => product.id === id
      );

      if (productIndex !== -1) {
        cartState.products[productIndex].quantity += 1;
      } else {
        cartState.products.push({
          id,
          quantity: 1,
        });
      }

      return cartState;
    });
  }

  function checkout(): void {
    initiateCheckout({
      lineItems: cartItems.map((item) => ({
        price: item.id,
        quantity: item.quantity,
      })),
    });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Space Jelly Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Space Jelly Shop</h1>

        <p className={styles.description}>
          The best space jellyfish swag on the web!
        </p>

        <p className={styles.description}>
          Items: {totalItems}
          <br />
          Total Cost: R${subtotal}
          <br />
          <button className={styles.button} onClick={checkout}>
            Check Out
          </button>
        </p>

        <ul className={styles.grid}>
          {products.map((product) => (
            <li key={product.id} className={styles.card}>
              <a href="#">
                <img src={product.image} alt={product.title} />
                <h2>{product.title}</h2>
                <p>R${product.price}</p>
                <p>{product.description}</p>
              </a>
              <p>
                <button
                  className={styles.button}
                  onClick={() => addToCart({ id: product.id })}
                >
                  Add to Cart
                </button>
              </p>
            </li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
